{
    'name': 'Odoo Development Tutorials By Yasin',
    'version': '13.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Odoo Development Tutorials For Beginners By Yasin Shaikh',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Yasin Shaikh',
    'maintainer': 'Yasin Shaikh',
    'website': 'odoomates.com',
    'live_test_url': 'https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1',
    'depends': ['sale','board'],
    'demo': [],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'data/cron.xml',
        'data/mail_template.xml',
        'wizard/create_appointment.xml',
        'views/patient.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'views/lab.xml',
        'views/dashboard.xml',        
        'views/sale_order.xml',        
        'views/settings.xml',
        'views/server_action.xml',
        'report/patient_card.xml',
        'report/report.xml',
        'report/sale_report_inherit.xml',
        'report/appointment.xml',
    ],
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
# Video Explanation: https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1
